apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-web
  labels:
    app: react-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-web
  template:
    metadata:
      labels:
        app: react-web
    spec:
      containers:
        - name: nginx
          image: myreact:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: react-web-svc
spec:
  selector:
    app: react-web
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
